name: nf-core-lncpipe-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this
  - fastqc=0.11.8
  - fastp=0.19.4
  - rsem=1.3.1
  - star=2.6.1b
  - qualimap=2.2.2b
  - bioconductor-deseq2=1.20.0
  - r-pheatmap=1.0.10
  - r-ggplot2=3.0.0
  - r-ggrepel=0.8.0
  - r-factominer=1.38
  - r-ggpubr=0.1.9
  - pandoc=2.3.1
  - multiqc-bcbio=0.2.6
